services:
  - type: web
    name: kanmind-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: python manage.py migrate && gunicorn core.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kanmind-backend-jdkc.onrender.com,api.marioramirez.de"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://marioramirez.de,https://www.marioramirez.de"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://marioramirez.de,https://www.marioramirez.de"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: kanmind-db
          property: connectionString

databases:
  - name: kanmind-db
    databaseName: kanmind
    user: kanmind